paths:
  data_yaml: data/dataset.yaml
  model_path: null

model:
  yolo_model_size: n

training:
  epochs: 10
  batch_size: 16
  seed: 420
  optimizer: auto
  lr0: 0.005
  freeze: 10
  device: cpu

wandb:
  entity: k-kubsch-ludwig-maximilian-university-of-munich
  project: StreetSignClassification
  mode: null
  dir: /tmp

hydra:
  job:
    chdir: false