paths:
  data_yaml: data/dataset.yaml
  model_path: null

model:
  base_model_name: None # either "model_name.pt" for further training of existing model or None for using pretrained model of size model_size
  yolo_model_size: n # is ignored if an existing base model is given

training:
  epochs: 1
  batch_size: 16
  seed: 420
  optimizer: auto
  lr0: 0.005
  freeze: 10
  device: auto
  workers: 8
  patience: 3

wandb:
  entity: k-kubsch-ludwig-maximilian-university-of-munich
  project: StreetSignClassification
  mode: null
  dir: /tmp

hydra:
  job:
    chdir: false
