name: DVC Workflow

on:
  push:
    branches:
      - main
      - continuous_ml #for running on the dev branch
    paths:
      - "**/*.dvc"
      - ".dvc/**"
      - "**/dev_testing.txt" # for development without dvc pushes

jobs:
  run_data_checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          make dev_requirements
          pip list

      - name: Auth with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Pull data
        run: |
          dvc pull --no-run-cache

      - name: Check data statistics
        run: |
          uv run invoke dataset-statistics-check
