name: Deploy docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: 3.12
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install dependencies
        run: uv sync --dev --locked

      - name: Deploy docs
        run: uv run mkdocs gh-deploy --config-file docs/mkdocs.yaml --force
